"""added the database to add natural disaster council data

Revision ID: bfc9773f1a84
Revises: 75c7f200b38c
Create Date: 2020-04-15 18:36:10.359622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc9773f1a84'
down_revision = '75c7f200b38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CouncilDisasterData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('council', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('calamity_1', sa.Text(), nullable=True),
    sa.Column('calamity_2', sa.Text(), nullable=True),
    sa.Column('calamity_3', sa.Text(), nullable=True),
    sa.Column('calamity_4', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CouncilDisasterData')
    # ### end Alembic commands ###
